/**
 * Sports catalog — searchable series with seasonal events.
 *
 * Data lives in src/data/sports-catalog.json (schema v2), generated by
 * scripts/build-sports-data.mjs, which also publishes the same JSON to the
 * website feed (website/data/sports/v2/catalog.json). At runtime the app may
 * swap in a fresher catalog fetched from the feed via applyCatalog().
 *
 * Session shapes:
 *   fixed:  { id, name, type, date: 'YYYY-MM-DD', time: 'HH:MM' }
 *   window: { id, name, type: 'window', startDate, endDate, firstCallTime }
 */

import bundledCatalog from '../../data/sports-catalog.json' with { type: 'json' };

export const CATALOG_SCHEMA_VERSION = 2;

/** Per-sport identity used for markers and chips. */
export const SPORT_META = {
  motorsport: { label: 'Motorsport', color: 0xffd166, glyph: 'flag', short: 'F1' },
  football: { label: 'Football', color: 0x5ef2c2, glyph: 'ball', short: 'FB' },
  tennis: { label: 'Tennis', color: 0xb2ff59, glyph: 'racket', short: 'TN' },
  mma: { label: 'MMA', color: 0xff6b6b, glyph: 'octagon', short: 'UFC' },
  surfing: { label: 'Surfing', color: 0x4dc9ff, glyph: 'wave', short: 'WSL' },
  nfl: { label: 'American Football', color: 0xc77dff, glyph: 'helmet', short: 'NFL' },
  golf: { label: 'Golf', color: 0x80ed99, glyph: 'tee', short: 'GLF' },
  cycling: { label: 'Cycling', color: 0xffe066, glyph: 'wheel', short: 'CYC' },
  cricket: { label: 'Cricket', color: 0x90e0ef, glyph: 'bat', short: 'CKT' },
  rugby: { label: 'Rugby', color: 0xf4a261, glyph: 'oval', short: 'RUG' },
  athletics: { label: 'Athletics', color: 0xff9e6d, glyph: 'track', short: 'ATH' },
};

/** Hex string for CSS (e.g. status chips). */
export function sportColorCss(sport) {
  const c = SPORT_META[sport]?.color ?? 0x4dc9ff;
  return '#' + c.toString(16).padStart(6, '0');
}

/** Catalog age in hours, or null if unknown. */
export function catalogAgeHours(now = new Date()) {
  if (!CATALOG_INFO?.generatedAt) return null;
  const t = Date.parse(CATALOG_INFO.generatedAt);
  if (Number.isNaN(t)) return null;
  return (now.getTime() - t) / 3600000;
}

/** Human feed status for the UI badge. */
export function catalogFeedStatus(now = new Date(), staleHours = 48) {
  const age = catalogAgeHours(now);
  const origin = CATALOG_INFO?.origin || 'bundled';
  if (age == null) {
    return { state: 'unknown', label: 'Schedules · bundled', detail: 'No generation timestamp', origin, ageHours: null };
  }
  if (age > staleHours) {
    return {
      state: 'stale',
      label: 'Schedules may be stale',
      detail: `Last refresh ~${Math.round(age)}h ago (${origin})`,
      origin,
      ageHours: age,
    };
  }
  if (origin === 'bundled') {
    return {
      state: 'bundled',
      label: 'Schedules · offline snapshot',
      detail: `Bundled data · ${Math.round(age)}h old`,
      origin,
      ageHours: age,
    };
  }
  return {
    state: 'fresh',
    label: 'Schedules up to date',
    detail: `Feed · updated ${Math.round(age)}h ago`,
    origin,
    ageHours: age,
  };
}

/** Live binding — updated in place when a fresher feed catalog arrives. */
export let SPORT_SERIES = bundledCatalog.series;
export let CATALOG_INFO = {
  schemaVersion: bundledCatalog.schemaVersion,
  generatedAt: bundledCatalog.generatedAt,
  origin: 'bundled',
};

const changeListeners = new Set();

/** Subscribe to catalog swaps. Returns unsubscribe. */
export function onCatalogChange(fn) {
  changeListeners.add(fn);
  return () => changeListeners.delete(fn);
}

/**
 * Validate + apply a remote catalog. Returns true if applied.
 * Rejects unknown schema versions and structurally broken payloads —
 * a bad feed must never take down the bundled data.
 */
export function applyCatalog(catalog, origin = 'feed') {
  if (!catalog || catalog.schemaVersion !== CATALOG_SCHEMA_VERSION) return false;
  if (!Array.isArray(catalog.series) || !catalog.series.length) return false;
  for (const s of catalog.series) {
    if (!s.id || !s.name || !Array.isArray(s.events)) return false;
    for (const e of s.events) {
      if (!e.id || typeof e.lat !== 'number' || typeof e.lng !== 'number' || !e.tz) return false;
      if (!Array.isArray(e.sessions) || !e.sessions.length) return false;
    }
  }
  SPORT_SERIES = catalog.series;
  CATALOG_INFO = {
    schemaVersion: catalog.schemaVersion,
    generatedAt: catalog.generatedAt || null,
    origin,
  };
  for (const fn of changeListeners) {
    try {
      fn(CATALOG_INFO);
    } catch {
      /* listener errors must not break the swap */
    }
  }
  return true;
}

export function getSeriesById(id) {
  return SPORT_SERIES.find((s) => s.id === id);
}

export function findEventById(eventId) {
  for (const s of SPORT_SERIES) {
    const e = s.events.find((ev) => ev.id === eventId);
    if (e) return { series: s, event: e };
  }
  return null;
}

export function searchSports(query) {
  const q = query.trim().toLowerCase();
  if (!q) return SPORT_SERIES.slice();
  const scored = [];
  for (const s of SPORT_SERIES) {
    let score = 0;
    const hay = [s.name, s.sport, s.category, s.season, s.description, ...(s.tags || [])].join(' ').toLowerCase();
    if (hay.includes(q)) score += 50;
    if (s.name.toLowerCase().includes(q)) score += 40;
    if ((s.tags || []).some((t) => t === q || t.includes(q))) score += 30;
    for (const e of s.events) {
      const eh = [e.name, e.city, e.country, ...(e.tags || [])].join(' ').toLowerCase();
      if (eh.includes(q)) score += 15;
    }
    if (score > 0) scored.push({ series: s, score });
  }
  scored.sort((a, b) => b.score - a.score);
  return scored.map((x) => x.series);
}

/**
 * Search individual events across all series ("silverstone", "ufc 330",
 * "teahupoo"). Returns [{ series, event, score }] best-first.
 */
export function searchEvents(query, limit = 10) {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  const scored = [];
  for (const s of SPORT_SERIES) {
    for (const e of s.events) {
      let score = 0;
      const name = e.name.toLowerCase();
      if (name === q) score = 100;
      else if (name.includes(q)) score = 70;
      const hay = [e.city, e.country, ...(e.tags || [])].join(' ').toLowerCase();
      if (hay.includes(q)) score = Math.max(score, 45);
      const words = q.split(/\s+/);
      if (words.length > 1 && words.every((w) => (name + ' ' + hay).includes(w))) {
        score = Math.max(score, 60);
      }
      if (score > 0) scored.push({ series: s, event: e, score });
    }
  }
  scored.sort((a, b) => b.score - a.score);
  return scored.slice(0, limit);
}
